version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: .github/workflows
  schedule:
    interval: weekly
  commit-message:
    prefix: "chore(deps): update GitHub Actions workflows"
  labels:
    - github-actions
